language: elixir
elixir:
  - 1.5.3
otp_release:
  - 18.3.4.8
sudo: false
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - mikalai.seva@gmail.com
