name: Runs on master branch or on open pull requests that are ready for review

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event_name == 'pull_request' && format('refs/heads/{0}', github.event.pull_request.head.ref) || github.ref }}

jobs:
  test:
    # This condition ensures that this job will not run on pull requests in draft state
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        otp: [24, 25, 26]
        elixir: [1.15]
    runs-on: ${{matrix.os}}
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} (${{matrix.os}})
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}
      - uses: erlef/setup-beam@v1.16.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Compile project
        run: mix compile --warnings-as-errors
      - name: Check formatting
        run: mix format --check-formatted
      - name: Check style
        run: mix credo --format flycheck
      - name: Run tests
        run: mix test  --cover
